=begin
#Kubernetes

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.13.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubernetes::ApiextensionsV1beta1WebhookClientConfig
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApiextensionsV1beta1WebhookClientConfig' do
  before do
    # run before each test
    @instance = Kubernetes::ApiextensionsV1beta1WebhookClientConfig.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApiextensionsV1beta1WebhookClientConfig' do
    it 'should create an instance of ApiextensionsV1beta1WebhookClientConfig' do
      expect(@instance).to be_instance_of(Kubernetes::ApiextensionsV1beta1WebhookClientConfig)
    end
  end
  describe 'test attribute "ca_bundle"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "service"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

