=begin
#Kubernetes

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.13.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubernetes::PolicyV1beta1IDRange
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PolicyV1beta1IDRange' do
  before do
    # run before each test
    @instance = Kubernetes::PolicyV1beta1IDRange.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PolicyV1beta1IDRange' do
    it 'should create an instance of PolicyV1beta1IDRange' do
      expect(@instance).to be_instance_of(Kubernetes::PolicyV1beta1IDRange)
    end
  end
  describe 'test attribute "max"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "min"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

