=begin
#Kubernetes

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1.13.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kubernetes::V1alpha1VolumeAttachmentStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V1alpha1VolumeAttachmentStatus' do
  before do
    # run before each test
    @instance = Kubernetes::V1alpha1VolumeAttachmentStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1alpha1VolumeAttachmentStatus' do
    it 'should create an instance of V1alpha1VolumeAttachmentStatus' do
      expect(@instance).to be_instance_of(Kubernetes::V1alpha1VolumeAttachmentStatus)
    end
  end
  describe 'test attribute "attach_error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attached"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "attachment_metadata"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "detach_error"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

